---
- name: Launch instance
  ec2:
    key_name: "{{ ec2_key_name }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    instance_profile_name: "{{ ec2_instance_profile_name }}"
    wait: yes
    group: ['Outbound Open', 'Inbound ssh lib-amz-broker']
    instance_tags:
      Name: "{{ec2_tag_Name}}"
      Unit: "{{ec2_tag_Unit}}"
      Workload: Unprovisioned
      App: "{{ec2_tag_App}}"
    exact_count: "{{ec2_exact_count}}"
    count_tag:
      App: "{{ec2_tag_App}}"
      Workload: "{{ec2_tag_Workload}}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    assign_public_ip: yes
    region: us-east-1
    volumes:
    - device_name: /dev/sda1
      device_type: gp2
      volume_size: "{{ ec2_volume_size }}"
      delete_on_termination: true
  register: ec2
- name: Wait 3 minutes
  wait_for: timeout=180
  when: ec2.changed == True
- name: Add instance to host group
  add_host: hostname={{ item.private_ip }} groupname=unprovisioned
  with_items: ec2.instances
  when: ec2.changed == True
- name: Set instance Name and ID as fact
  set_fact:
    server_tag_name: "{{ item.tags.Name }}"
    instance_id: "{{ item.id }}"
  with_items: "{{ ec2.tagged_instances }}"
