---
- name: Set instance default user and key to 1st user in vars
  set_fact:
    ec2_instance_default_user_name: "{{ item.1.name }}"
    ec2_key_name: "{{ item.1.keyname }}"
    ec2_key_material: "{{ item.1.pubkey }}"
  with_indexed_items: "{{ users }}"
  when: item.0 == 0
- name: ec2 key
  ec2_key:
    name: "{{ hostvars['localhost']['ec2_key_name'] }}"
    key_material: "{{ hostvars['localhost']['ec2_key_material'] }}"
    region: us-east-1
    state: present
- name: refresh inventory
  meta: refresh_inventory
- name: Launch instance
  ec2:
    key_name: "{{ hostvars['localhost']['ec2_key_name'] }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    instance_profile_name: "{{ ec2_instance_profile_name }}"
    user_data: |
      #cloud-config
      system_info:
        default_user:
          name: "{{ hostvars['localhost']['ec2_instance_default_user_name'] }}"
    wait: yes
    group: ['Outbound Open', 'Inbound ssh lib-amz-broker']
    instance_tags:
      Name: "{{ ec2_tag_Name }}"
      Unit: "{{ ec2_tag_Unit }}"
      Workload: Unprovisioned
      App: "{{ ec2_tag_App }}"
    exact_count: "{{ ec2_exact_count }}"
    count_tag:
      App: "{{ ec2_tag_Name }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    assign_public_ip: yes
    region: us-east-1
    volumes:
    - device_name: /dev/sda1
      device_type: gp2
      volume_size: "{{ ec2_volume_size }}"
      delete_on_termination: true
  register: ec2
- name: Wait 3 minutes
  wait_for: timeout=180
  when: ec2.changed == True
- name: Add instance to host group
  add_host: hostname={{ ec2_tag_Name }}
    groupname=ec2.unprovisioned
  when: ec2.changed == True
- name: Gather ec2 facts
  ec2_remote_facts:
    region: 'us-east-1'
    filters:
      instance-state-name: running
      subnet-id: "{{ ec2_vpc_subnet_id }}"
      "tag:Name": "{{ ec2_tag_Name }}"
      "tag:Unit": "{{ ec2_tag_Unit }}"
      "tag:Workload": Unprovisioned
      "tag:App": "{{ ec2_tag_App }}"
  register: ec2_info
- name: Set Name, intended workload, private_ip, region, and ID as fact
  set_fact:
    server_tag_name: "{{ ec2_tag_Name }}"
    server_tag_workload: "{{ ec2_tag_Workload }}"
    instance_id: "{{ item.id }}"
    server_ip: "{{ item.private_ip_address }}"
    region: "{{ item.region }}"
  with_items: "{{ ec2_info.instances }}"
